# .github/workflows/deploy.yml
#
# Auto-deploy ke GitHub Pages setiap push ke branch main
# Otomatis inject PROD config dari GitHub Secrets

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Inject prod credentials dari GitHub Secrets ke config.js
      - name: Create config.js
        run: |
          cat > js/config.js << CONF
          const SUPABASE_URL = '${{ secrets.SUPABASE_URL }}';
          const SUPABASE_ANON_KEY = '${{ secrets.SUPABASE_ANON_KEY }}';
          const ENV = 'prod';
          CONF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,*.sh,supabase,js/config.dev.js,js/config.prod.js'
