# .github/workflows/deploy.yml
#
# Auto-deploy ke GitHub Pages setiap push ke branch main
# Otomatis inject PROD config dari GitHub Secrets

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.js
        run: |
          printf "const SUPABASE_URL = '%s';\nconst SUPABASE_ANON_KEY = '%s';\nconst ENV = 'prod';\n" \
            "${{ secrets.SUPABASE_URL }}" \
            "${{ secrets.SUPABASE_ANON_KEY }}" \
            > js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,*.sh,supabase,js/config.dev.js,js/config.prod.js'